### ISSUE TITLE
iml-supervisor-status and iml-srcmap-reverse need to require nodejs

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/manager-for-lustre-dependencies#29]
It appears that you can install either `iml-supervisor-status` or `iml-srcmap-reverse` without nodejs as a dep. 

When this occurs there is a cryptic: 

`failed to listen on sockets: No such file or directory` error when trying to start the socket.

I think there is the same issue intermittently during install time in IML, where if one of these packages is installed before node it will run the `%post` block and skip with the same error.

Make sure that these packages list node as a requirement in some way.

**Comment by johnsonw** [comment]
Interesting, so the order is definitely important here. Since we are using yum, we can probably indicate that nodejs is a dependency, right?

**Comment by jgrund** [comment]
We should be able to do so in the spec file. I need to review https://fedoraproject.org/wiki/Packaging:Node.js again for their recommended approach.

**Comment by jgrund** [comment]
This is somewhat unrelated but interesting: https://www.npmjs.com/package/speculate

**Comment by johnsonw** [comment]
Interesting you bring this up. I saw this last week while researching socket activation and some examples with node.  I wish I still had the link handy, but what seemed nice is that it generated a lot of stuff for you.

**Comment by johnsonw** [comment]
As a side note, I didn't dive into too deeply because I wanted to have a better understanding of spec files and I felt that if I relied on something like speculate I wouldn't have as good of an understanding. That being said, if it does a good job, i'm sure it will prevent errors like this one.

**Comment by jgrund** [comment]
Well, it looks like it just builds a spec file from your `package.json` using a mustache template.

The relevant bit would be this I think: https://github.com/bbc/speculate/blob/master/templates/spec.mustache#L15

**Comment by johnsonw** [comment]
Nice, this looks like what we need 👍
